// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bubkvzzkicqgebwczrsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1Ymt2enpraWNxZ2Vid2N6cnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODM0ODAsImV4cCI6MjA3MzE1OTQ4MH0.z4As-wUv7Gr-IV1akYt3aQPklU06Opw71rnvc0XG4dU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});